services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: harmony
      POSTGRES_PASSWORD: harmony
      POSTGRES_DB: harmony_hours
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
